import logging
import tempfile
from pathlib import Path

import torch
from jaxtyping import Float
from openbabel import openbabel
from rdkit import Chem

from sampling.moe_layout import COORDS_DIM

logger = logging.getLogger(__name__)


class MoleculeBuilder:
    """Build RDKit molecules from generated point-cloud atom features."""

    @classmethod
    def xyz_blocks_from_batch(
        cls,
        xh: Float[torch.Tensor, "B lig feature"],
        fragment_atom_types: torch.Tensor | None = None,
        atom_type_decoder: dict[int, str] | None = None,
        atom_type_dim: int | None = None,
    ) -> list[str]:
        if atom_type_decoder is None:
            raise ValueError("atom_type_decoder is required because atom vocabulary is defined by DynamicMoELayout.")
        if atom_type_dim is None:
            raise ValueError("atom_type_dim is required because atom vocabulary is defined by DynamicMoELayout.")

        coordinates = xh[..., :COORDS_DIM].detach().cpu()
        atom_features = xh[..., COORDS_DIM : COORDS_DIM + atom_type_dim]
        atom_types = atom_features.argmax(-1).detach().cpu()

        if fragment_atom_types is not None:
            logger.info(
                "We assume that the fragment is always at the beginning of the atom types. "
                "If this assumption is violated, please check your input data."
            )

        xyz_blocks = []
        for coordinates_sample, atom_types_sample in zip(coordinates, atom_types):
            atom_types_sample = atom_types_sample.clone()
            if fragment_atom_types is not None:
                atom_types_sample[: len(fragment_atom_types)] = fragment_atom_types.detach().cpu()
            xyz_blocks.append(
                cls.to_xyz_block(coordinates_sample, atom_types_sample, atom_type_decoder=atom_type_decoder)
            )

        return xyz_blocks

    @staticmethod
    def to_xyz_block(
        coordinates: Float[torch.Tensor, "lig coords"],
        atom_types: torch.Tensor,
        atom_type_decoder: dict[int, str] | None = None,
    ) -> str:
        if atom_type_decoder is None:
            raise ValueError("atom_type_decoder is required because atom vocabulary is defined by DynamicMoELayout.")

        lines = [str(len(atom_types)), "generated by ACE-for-SBDD"]
        for coordinate, atom_type in zip(coordinates, atom_types):
            atom_type_idx = int(atom_type.item())
            if atom_type_idx not in atom_type_decoder:
                raise ValueError(f"Unsupported atom type index {atom_type_idx}.")
            symbol = atom_type_decoder[atom_type_idx]
            if symbol == "others":
                raise ValueError("Cannot write an XYZ atom with symbolic atom type 'others'.")
            x, y, z = coordinate.tolist()
            lines.append(f"{symbol} {float(x):.9f} {float(y):.9f} {float(z):.9f}")

        return "\n".join(lines) + "\n"

    @staticmethod
    def build_mols_from_xyz_blocks(xyz_blocks: list[str]) -> list[Chem.Mol | None]:
        return [MoleculeBuilder.build_mols_from_xyz_block(xyz_block) for xyz_block in xyz_blocks]

    @staticmethod
    def build_mols_from_xyz_block(xyz_block: str) -> Chem.Mol | None:
        """
        Use OpenBabel as a bond-order guesser.
        Returns None if OpenBabel fails or produces a molecule that RDKit cannot sanitize.
        """
        rdkit_mol = Chem.MolFromXYZBlock(xyz_block)
        if rdkit_mol is None:
            logger.error("RDKit failed to parse generated XYZ block.")
            return None

        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir_path = Path(tmpdir)
            xyz_path = tmpdir_path / "input.xyz"
            sdf_path = tmpdir_path / "output.sdf"

            xyz_path.write_text(xyz_block)

            if not MoleculeBuilder._convert_xyz_to_sdf_with_openbabel(xyz_path, sdf_path):
                return None

            if not sdf_path.exists() or sdf_path.stat().st_size == 0:
                logger.error("OpenBabel produced an empty SDF file.")
                return None

            supplier = Chem.SDMolSupplier(str(sdf_path), sanitize=False, removeHs=False)

            ob_mol = next((mol for mol in supplier if mol is not None), None)
            if ob_mol is None:
                logger.error("RDKit failed to read OpenBabel-generated SDF.")
                return None

        # Fresh copy removes problematic noImplicit/radical state while preserving
        # OpenBabel-guessed bond orders and formal charges.
        copied = MoleculeBuilder._copy_atoms_bonds_and_conformer(ob_mol)

        return copied

    @staticmethod
    def _convert_xyz_to_sdf_with_openbabel(xyz_path: Path, sdf_path: Path) -> bool:
        try:
            conversion = openbabel.OBConversion()
            conversion.SetInAndOutFormats("xyz", "sdf")

            ob_mol = openbabel.OBMol()
            conversion.ReadFile(ob_mol, str(xyz_path))
            conversion.WriteFile(ob_mol, str(sdf_path))
        except Exception as exc:
            logger.error("OpenBabel Python conversion failed: %s", exc)
            return False

        return True

    @staticmethod
    def _copy_atoms_bonds_and_conformer(mol: Chem.Mol) -> Chem.Mol:
        """
        Copy only atoms, bonds, charges, aromatic flags, and conformer.

        This intentionally creates fresh RDKit atoms so that noImplicit/radical
        state from XYZ or perception backends does not leak into the final mol.
        """
        copied = Chem.RWMol()

        for atom in mol.GetAtoms():
            new_atom = Chem.Atom(atom.GetAtomicNum())

            new_atom.SetIsotope(atom.GetIsotope())
            new_atom.SetFormalCharge(atom.GetFormalCharge())

            # Important for heavy-atom-only XYZ workflows.
            new_atom.SetNoImplicit(False)
            new_atom.SetNumRadicalElectrons(0)

            copied.AddAtom(new_atom)

        for bond in mol.GetBonds():
            begin_idx = bond.GetBeginAtomIdx()
            end_idx = bond.GetEndAtomIdx()

            bond_type = bond.GetBondType()
            if bond_type == Chem.BondType.UNSPECIFIED:
                bond_type = Chem.BondType.SINGLE

            copied.AddBond(begin_idx, end_idx, bond_type)

            new_bond = copied.GetBondBetweenAtoms(begin_idx, end_idx)
            if new_bond is None:
                raise RuntimeError(f"Failed to copy bond: {begin_idx}-{end_idx}")

            is_aromatic = bond.GetIsAromatic() or bond_type == Chem.BondType.AROMATIC
            new_bond.SetIsAromatic(is_aromatic)

            if is_aromatic:
                copied.GetAtomWithIdx(begin_idx).SetIsAromatic(True)
                copied.GetAtomWithIdx(end_idx).SetIsAromatic(True)

        copied_mol = copied.GetMol()

        if mol.GetNumConformers() > 0:
            source_conf = mol.GetConformer(0)
            conf = Chem.Conformer(mol.GetNumAtoms())
            conf.Set3D(True)

            for atom_idx in range(mol.GetNumAtoms()):
                conf.SetAtomPosition(atom_idx, source_conf.GetAtomPosition(atom_idx))

            copied_mol.AddConformer(conf, assignId=True)

        return copied_mol
